### ISSUE TITLE
install_software.sh directory mismatch

### ISSUE THREAD

**Issue by fishr** [mit212/me212bashrc#2]
I couldn't tell what the intended behavior is supposed to be, so I'm marking this as a bug.  Lines 133-138 in install_software.sh attempts to copy files for the dynamixel ros package to a folder of its own creating.  However, a fresh install of this package shows the files aren't where the script expects them to be (they are inside a folder, models, already) so it fails at copying them.

Was the separate folder to provide update protection in case an update breaks peoples' robots?

**Comment by peterkty** [comment]
Those files were not at the proper place when we installed the package last year. If they are already there means they fixed the issue. Then we don't need those lines. Just remove them.

Peter
